# Generated by Django 5.2.3 on 2025-09-15 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appchevrolet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='vehiculos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=100)),
                ('marca', models.CharField(max_length=40)),
                ('categoria', models.CharField(max_length=40)),
                ('motor', models.TextField()),
                ('contenido', models.TextField()),
                ('imagen', models.ImageField(upload_to='media_vehiculos')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='chevys',
        ),
    ]
