# Generated by Django 5.2.3 on 2025-09-07 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apphome', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='home',
            new_name='homes',
        ),
    ]
