# Generated by Django 5.2.3 on 2025-09-14 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apphome', '0002_rename_home_homes'),
    ]

    operations = [
        migrations.CreateModel(
            name='sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('imagen', models.ImageField(upload_to='media_home')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='homes',
        ),
    ]
