# Generated by Django 5.2.3 on 2025-09-06 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptoyota', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toyotas',
            name='contenido',
            field=models.TextField(),
        ),
    ]
