# Generated by Django 5.2.3 on 2025-09-16 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptoyota', '0002_alter_toyotas_contenido'),
    ]

    operations = [
        migrations.CreateModel(
            name='hoteles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('distancia', models.TextField()),
                ('imagen', models.ImageField(upload_to='media_hoteles')),
                ('precio', models.CharField(max_length=80)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='toyotas',
        ),
    ]
